// apps/web/src/components/layouts/Header.tsx
import { MenuFoldOutlined, MenuUnfoldOutlined } from '@ant-design/icons';
import { Avatar, Button, Layout, Space, Typography } from 'antd';
import type { BreadcrumbProps } from 'antd';
import { LayoutBreadcrumb } from './Breadcrumb';

const { Header: AntHeader } = Layout;

export type LayoutHeaderProps = {
    breadcrumbItems?: BreadcrumbProps['items'];
    collapsed?: boolean;
    title?: string;
    onToggleSider?: () => void;
};

export function LayoutHeader({
    breadcrumbItems,
    collapsed = false,
    onToggleSider,
}: LayoutHeaderProps) {
    return (
        <AntHeader className="layout-header">
            <Space align="center" size={16}>
                <Button
                    aria-label={collapsed ? '展开菜单栏' : '收起菜单栏'}
                    icon={collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
                    onClick={onToggleSider}
                    type="text"
                />
                <LayoutBreadcrumb items={breadcrumbItems} />
            </Space>
            <Space align="center" size={12}>
                <Typography.Text type="secondary">管理员</Typography.Text>
                <Avatar>AI</Avatar>
            </Space>
        </AntHeader>
    );
}

export default LayoutHeader;

// apps/web/src/components/layouts/Header.vue
<script setup>
import { MenuFoldOutlined, MenuUnfoldOutlined } from '@ant-design/icons-vue';
import LayoutBreadcrumb from './Breadcrumb.vue';

defineProps({
    breadcrumbItems: {
        type: Array,
        default: () => [],
    },
    collapsed: {
        type: Boolean,
        default: false,
    },
});

defineEmits(['toggle-sider']);
</script>

<template>
    <a-flex class="layout-header" align="center" justify="space-between">
        <a-space align="center" :size="16">
            <a-button
                :aria-label="collapsed ? '展开菜单栏' : '收起菜单栏'"
                type="text"
                @click="$emit('toggle-sider')"
            >
                <template #icon>
                    <MenuUnfoldOutlined v-if="collapsed" />
                    <MenuFoldOutlined v-else />
                </template>
            </a-button>
            <LayoutBreadcrumb :items="breadcrumbItems" />
        </a-space>
        <a-space align="center" :size="12">
            <a-typography-text class="layout-header__user-label" type="secondary">
                管理员
            </a-typography-text>
            <a-avatar>AI</a-avatar>
        </a-space>
    </a-flex>
</template>

<style scoped>
.layout-header {
    flex: 0 0 64px;
    height: 64px;
    min-width: 0;
    padding: 0 24px;
}

@media (max-width: 768px) {
    .layout-header {
        padding: 0 16px;
    }

    .layout-header__user-label {
        display: none;
    }
}
</style>
