// apps/web/src/components/layouts/Main.tsx
import { Layout } from 'antd';
import type { MenuProps } from 'antd';
import { useMemo, useState } from 'react';
import { Outlet, useLocation, useNavigate } from 'react-router-dom';
import {
    defaultMenuPath,
    getBreadcrumbItems,
    getMenuItemByPath,
    getMenuPathKeys,
} from '../../data/menuData';
import { getRouteMeta } from '../../data/routeMeta';

import { LayoutContent } from './Content';
import { LayoutFooter } from './Footer';
import { LayoutHeader } from './Header';
import { LayoutSider } from './Sider';

export function MainLayout() {
    const location = useLocation();
    const navigate = useNavigate();
    const [collapsed, setCollapsed] = useState(false);
    const [menuState, setMenuState] = useState<{ keys: string[]; path: string } | null>(null);

    const activeMenuItem = getMenuItemByPath(location.pathname);
    const activeRouteMeta = getRouteMeta(location.pathname);
    const activePath = activeMenuItem?.path ?? defaultMenuPath;
    const activeMenuKeys = useMemo(() => getMenuPathKeys(activePath), [activePath]);
    const activeOpenMenuKeys = useMemo(
        () => (activeMenuItem ? activeMenuKeys.slice(0, -1) : []),
        [activeMenuItem, activeMenuKeys],
    );
    const breadcrumbItems = useMemo(() => {
        if (activeMenuItem) {
            return getBreadcrumbItems(activePath);
        }

        return activeRouteMeta?.breadcrumbItems ?? [{ title: '首页' }, { title: '页面不存在' }];
    }, [activeRouteMeta, activeMenuItem, activePath]);
    const title = activeMenuItem?.label ?? activeRouteMeta?.title ?? '页面不存在';
    const openMenuKeys = menuState?.path === activePath ? menuState.keys : activeOpenMenuKeys;

    const handleMenuSelect: MenuProps['onSelect'] = ({ key }) => {
        navigate(String(key));
    };

    const handleMenuOpenChange: MenuProps['onOpenChange'] = (keys) => {
        setMenuState({ keys: keys.map(String), path: activePath });
    };

    return (
        <Layout className="app-layout">
            <LayoutSider
                collapsed={collapsed}
                onCollapse={setCollapsed}
                onMenuOpenChange={handleMenuOpenChange}
                onMenuSelect={handleMenuSelect}
                openKeys={openMenuKeys}
                selectedKey={activeMenuItem ? activePath : undefined}
            />
            <Layout className="app-layout__body">
                <LayoutHeader
                    breadcrumbItems={breadcrumbItems}
                    collapsed={collapsed}
                    onToggleSider={() => setCollapsed((value) => !value)}
                    title={title}
                />
                <main className="app-layout__main">
                    <LayoutContent>
                        <Outlet />
                    </LayoutContent>
                </main>
                <LayoutFooter />
            </Layout>
        </Layout>
    );
}

export default MainLayout;

// apps/web/src/components/layouts/Main.vue
<script setup>
import { computed, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import {
    defaultMenuPath,
    getBreadcrumbItems,
    getMenuItemByPath,
    getMenuPathKeys,
} from '../../data/menuData.js';
import { getRouteMeta } from '../../data/routeMeta.js';
import LayoutContent from './Content.vue';
import LayoutFooter from './Footer.vue';
import LayoutHeader from './Header.vue';
import LayoutSider from './Sider.vue';

const route = useRoute();
const router = useRouter();
const collapsed = ref(false);
const menuState = ref(null);

const activeMenuItem = computed(() => getMenuItemByPath(route.path));
const activeRouteMeta = computed(() => getRouteMeta(route.path));
const activePath = computed(() => activeMenuItem.value?.path ?? defaultMenuPath);
const activeMenuKeys = computed(() => getMenuPathKeys(activePath.value));
const activeOpenMenuKeys = computed(() =>
    activeMenuItem.value ? activeMenuKeys.value.slice(0, -1) : [],
);
const breadcrumbItems = computed(() => {
    if (activeMenuItem.value) {
        return getBreadcrumbItems(activePath.value);
    }

    return activeRouteMeta.value?.breadcrumbItems ?? [{ title: '首页' }, { title: '页面不存在' }];
});
const openMenuKeys = computed(() =>
    menuState.value?.path === activePath.value ? menuState.value.keys : activeOpenMenuKeys.value,
);

function handleMenuSelect({ key }) {
    router.push(String(key));
}

function handleMenuOpenChange(keys) {
    menuState.value = { keys: keys.map(String), path: activePath.value };
}
</script>

<template>
    <a-layout class="app-layout">
        <LayoutSider
            :collapsed="collapsed"
            :open-keys="openMenuKeys"
            :selected-key="activeMenuItem ? activePath : undefined"
            @collapse="collapsed = $event"
            @menu-open-change="handleMenuOpenChange"
            @menu-select="handleMenuSelect"
        />
        <a-layout class="app-layout__body">
            <LayoutHeader
                :breadcrumb-items="breadcrumbItems"
                :collapsed="collapsed"
                @toggle-sider="collapsed = !collapsed"
            />
            <main class="app-layout__main">
                <LayoutContent>
                    <RouterView />
                </LayoutContent>
            </main>
            <LayoutFooter />
        </a-layout>
    </a-layout>
</template>
