// apps/web/src/pages/chat/ChatPage.tsx
import { Button, Card, Empty, Input, List, Space, Typography } from 'antd';
import { useState } from 'react';
import styles from './ChatPage.module.css';

const { TextArea } = Input;

interface ChatMessage {
    id: string;
    role: 'user' | 'assistant';
    content: string;
    createdAt: string;
}

const initialMessages: ChatMessage[] = [
    {
        id: 'welcome',
        role: 'assistant',
        content: '你好，我是 Boring Chat。你可以先把这里接成本地 mock，后续再替换成真实后端接口。',
        createdAt: new Date().toISOString(),
    },
];

function createMessage(role: ChatMessage['role'], content: string): ChatMessage {
    return {
        id: crypto.randomUUID(),
        role,
        content,
        createdAt: new Date().toISOString(),
    };
}

export function ChatPage() {
    const [messages, setMessages] = useState<ChatMessage[]>(initialMessages);
    const [inputValue, setInputValue] = useState('');

    const handleSend = () => {
        const content = inputValue.trim();

        if (!content) {
            return;
        }

        const userMessage = createMessage('user', content);
        const assistantMessage = createMessage(
            'assistant',
            `已收到：${content}\n\n这里后续可以替换为 fetch('/api/chat') 或 SSE 流式响应。`,
        );

        setMessages((currentMessages) => [...currentMessages, userMessage, assistantMessage]);
        setInputValue('');
    };

    return (
        <div className={styles.page}>
            <Card className={styles.panel} title="Boring Chat">
                {messages.length === 0 ? (
                    <Empty description="暂无消息" />
                ) : (
                    <List
                        className={styles.messages}
                        dataSource={messages}
                        renderItem={(message) => (
                            <List.Item
                                className={`${styles.message} ${
                                    message.role === 'user' ? styles.userMessage : ''
                                }`}
                            >
                                <div className={styles.bubble}>
                                    <Typography.Text strong>
                                        {message.role === 'user' ? '你' : '助手'}
                                    </Typography.Text>
                                    <Typography.Paragraph className={styles.content}>
                                        {message.content}
                                    </Typography.Paragraph>
                                </div>
                            </List.Item>
                        )}
                    />
                )}
                <Space.Compact className={styles.composer}>
                    <TextArea
                        autoSize={{ minRows: 2, maxRows: 6 }}
                        onChange={(event) => setInputValue(event.target.value)}
                        onPressEnter={(event) => {
                            if (!event.shiftKey) {
                                event.preventDefault();
                                handleSend();
                            }
                        }}
                        placeholder="输入消息，Enter 发送，Shift + Enter 换行"
                        value={inputValue}
                    />
                    <Button type="primary" onClick={handleSend}>
                        发送
                    </Button>
                </Space.Compact>
            </Card>
        </div>
    );
}

export default ChatPage;

// apps/web/src/pages/chat/ChatPage.vue
<script setup>
import { ref } from 'vue';

const initialMessages = [
    {
        id: 'welcome',
        role: 'assistant',
        content: '你好，我是 Boring Chat。你可以先把这里接成本地 mock，后续再替换成真实后端接口。',
        createdAt: new Date().toISOString(),
    },
];

const messages = ref([...initialMessages]);
const inputValue = ref('');

function createMessage(role, content) {
    return {
        id: crypto.randomUUID(),
        role,
        content,
        createdAt: new Date().toISOString(),
    };
}

function handleSend() {
    const content = inputValue.value.trim();

    if (!content) {
        return;
    }

    messages.value.push(
        createMessage('user', content),
        createMessage(
            'assistant',
            `已收到：${content}\n\n这里后续可以替换为 fetch('/api/chat') 或 SSE 流式响应。`,
        ),
    );
    inputValue.value = '';
}

function handlePressEnter(event) {
    if (!event.shiftKey) {
        event.preventDefault();
        handleSend();
    }
}
</script>

<template>
    <div :class="$style.page">
        <a-card :class="$style.panel" title="Boring Chat">
            <a-empty v-if="messages.length === 0" description="暂无消息" />
            <a-list v-else :class="$style.messages" :data-source="messages">
                <template #renderItem="{ item }">
                    <a-list-item :class="item.role === 'user' ? $style.userMessage : undefined">
                        <a-card :class="$style.bubble" size="small">
                            <a-typography-text strong>
                                {{ item.role === 'user' ? '你' : '助手' }}
                            </a-typography-text>
                            <a-typography-paragraph :class="$style.content">
                                {{ item.content }}
                            </a-typography-paragraph>
                        </a-card>
                    </a-list-item>
                </template>
            </a-list>
            <a-space-compact :class="$style.composer">
                <a-textarea
                    v-model:value="inputValue"
                    :auto-size="{ minRows: 2, maxRows: 6 }"
                    placeholder="输入消息，Enter 发送，Shift + Enter 换行"
                    @press-enter="handlePressEnter"
                />
                <a-button type="primary" @click="handleSend">发送</a-button>
            </a-space-compact>
        </a-card>
    </div>
</template>

<style module>
.page {
    display: flex;
    flex: 1;
    height: 100%;
    min-height: 0;
    min-width: 0;
    width: 100%;
}

.panel {
    display: flex;
    flex: 1;
    flex-direction: column;
    height: 100%;
    min-height: 0;
    min-width: 0;
    overflow: hidden;
    width: 100%;
}

.panel :global(.ant-card-head) {
    flex: 0 0 auto;
}

.panel :global(.ant-card-body) {
    display: flex;
    flex: 1;
    flex-direction: column;
    min-height: 0;
    min-width: 0;
    overflow: hidden;
}

.messages {
    flex: 1;
    margin-bottom: 16px;
    min-height: 0;
    min-width: 0;
    overflow: auto;
}

.userMessage {
    justify-content: flex-end;
}

.bubble {
    max-width: min(720px, 84%);
}

.content {
    margin: 6px 0 0 !important;
    white-space: pre-wrap;
}

.composer {
    display: flex;
    flex: 0 0 auto;
    min-width: 0;
    width: 100%;
}

.composer :global(.ant-btn) {
    height: 100%;
}
</style>
