// apps/web/src/components/layouts/menu/Menu.tsx
import { Menu as AntMenu } from 'antd';
import type { MenuProps } from 'antd';
import { useMemo } from 'react';
import { menuData } from '../../../data/menuData';
import {
    createLayoutMenuItems,
    type CreateLayoutMenuItemsOptions,
    type LayoutMenuItem,
} from './menuItems';

export type LayoutMenuProps = CreateLayoutMenuItemsOptions & {
    items?: LayoutMenuItem[];
    collapsed?: boolean;
    mode?: MenuProps['mode'];
    openKeys?: string[];
    selectedKey?: string;
    theme?: MenuProps['theme'];
    onOpenChange?: MenuProps['onOpenChange'];
    onSelect?: MenuProps['onSelect'];
};

export function LayoutMenu({
    hasPermission,
    items,
    collapsed = false,
    mode = 'inline',
    openKeys,
    selectedKey,
    theme = 'light',
    onOpenChange,
    onSelect,
}: LayoutMenuProps) {
    const menuItems = useMemo(
        () => items ?? createLayoutMenuItems(menuData, { hasPermission }),
        [hasPermission, items],
    );

    return (
        <AntMenu
            items={menuItems}
            mode={mode}
            onOpenChange={onOpenChange}
            onSelect={onSelect}
            inlineCollapsed={mode === 'inline' ? collapsed : undefined}
            openKeys={mode === 'inline' ? openKeys : undefined}
            selectedKeys={selectedKey ? [selectedKey] : []}
            style={{ borderInlineEnd: 0 }}
            theme={theme}
        />
    );
}

export default LayoutMenu;

// apps/web/src/components/layouts/menu/Menu.vue
<script setup>
import { computed } from 'vue';
import { menuData } from '../../../data/menuData.js';
import { createLayoutMenuItems } from './menuItems.js';

const props = defineProps({
    hasPermission: {
        type: Function,
        default: undefined,
    },
    items: {
        type: Array,
        default: undefined,
    },
    mode: {
        type: String,
        default: 'inline',
    },
    openKeys: {
        type: Array,
        default: () => [],
    },
    selectedKey: {
        type: String,
        default: undefined,
    },
    theme: {
        type: String,
        default: 'light',
    },
});

defineEmits(['open-change', 'select']);

const menuItems = computed(
    () => props.items ?? createLayoutMenuItems(menuData, { hasPermission: props.hasPermission }),
);
</script>

<template>
    <a-menu
        :items="menuItems"
        :mode="mode"
        :open-keys="mode === 'inline' ? openKeys : undefined"
        :selected-keys="selectedKey ? [selectedKey] : []"
        :theme="theme"
        @open-change="$emit('open-change', $event)"
        @select="$emit('select', $event)"
    />
</template>
